version: "3"

services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        image: mvcbase/app:latest
        ports:
            - ${APP_PORT}:80
        networks:
            - appnet
        volumes:
            - ./src:/var/www/html/src
        working_dir: /var/www/html/src
    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: mvcbase/node:latest
        networks:
            - appnet
        volumes:
            - ./src:/var/www/html/src
        working_dir: /var/www/html/src
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - appnet
        volumes:
            - mysqldata:/var/lib/mysql
    postgres:
        image: postgres:11.6-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - appnet
        volumes:
            - postgresdata:/var/lib/postgresql/data
networks:
    appnet:
        driver: bridge
volumes:
    mysqldata:
        driver: local
    postgresdata:
        driver: local
